### ISSUE TITLE
since 1.3 none command is working

### ISSUE THREAD

**Issue by mirisbowring** [byYottaFLOPS/EasyScoreboards#2]
since the new 1.3, no scoreboard plugin command is working...
neither reload or set <line> <content>...
If i change the content in the config file, it's visible, but though i can't change anything ingame or via console...

**Comment by jonas-peeters** [comment]
Are you using the new commands?

`/scoreboard set <Line> <Text>`
`/scoreboard reload`
`/scoreboard countdown <set/start/stop/chat/title/xp>`
...

In case you do:
1. Which version of Sponge are you using?
2. Which version of Java do you have installed?
3. Is Sponge finding the plugin? (When you start the server you can see the number of plugins Sponge found in the 5. line)

**Comment by mirisbowring** [comment]
Yes, i am using the new commands.

Sponge Version: 1.8-1577-3.1.0-BETA-1045
Java Version: 1.8.0_66 x64
Yes...
First time starting it says config not found (logically) and creates one
Next time starting server it says:
config loaded 
config saved

And no errors

**Comment by jonas-peeters** [comment]
After a bit of research it seems to your Sponge version.

The 1.8 has it's own scoreboard commands and the plugin can't override them.
In the 1.8.9 the plugin work just fine for me.

You should probably update to the 1.8.9. If you can't do this for any reason, I'll can change the commands again, so that they won't overlap with Sponges own commands, but I think that I should do this anyways for compatibility reasons.

**Comment by mirisbowring** [comment]
If it is not a big circumstance, it would be nice if u port it to 1.8, because i am using many mods which are 1.8 only :)

**Comment by jonas-peeters** [comment]
The new release (v1.3.1) is working with `/easyscoreboard`.
Therefor it now works in the 1.8.

**Comment by mirisbowring** [comment]
Oh Thanks a lot :D
now everything works fine :)
